### ISSUE TITLE
App is running but no model is appears on the screen

### ISSUE THREAD

**Issue by tn-17** [mityu/yoMMD#158]
Hello, I was trying out the application and was unable to have the mmd model appear on the screen.

I downloaded this Miku mmd model https://bowlroll.net/file/173424
(password is `iwillkeeptherules` from the readme file)

My config.toml is

```
model = "./miku/編集用.pmx"
```

There is a system tray icon for the app and I am able to click on the settings such as Enable Mouse, selecting a screen, etc. However nothing is appearing on the screen and I am unsure if this is an issue with the mmd files I downloaded or a different issue.

Very cool project by the way :)

**Comment by mityu** [comment]
Probably yoMMD won't show any MMD models when no motion is given. (To be honest with you, I'm not sure this is right.  I already forgot what current yoMMD does or not :-})
Could you once try again with some motions (.vmd files) ?

To configure motions, these may help you:
- https://github.com/mityu/yoMMD?tab=readme-ov-file#example-configuration
- https://github.com/mityu/yoMMD/blob/main/doc/configuration.rst

**Comment by tn-17** [comment]
Missing motion was indeed the problem. The mmd model now appears on the screen. Thank you!

**Comment by mityu** [comment]
The latest release now shows the MMD model even if no motions are given ;)
